django_facturier/urls.py
from django.contrib import admin
from django.urls import path, include
from facturier.views import HomePageView, ClientCreateView, ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView
from devis.views import DevisListView, DevisDetailView, DevisCreateView, DevisUpdateView, DevisDeleteView, DevisPrintView, TransformDevisToFactureView
from facture.views import FactureListView, FactureDetailView, FacturePrintView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('register/', ClientCreateView.as_view(), name='register'),
    path('clients/', ClientListView.as_view(), name='list-client'),
    path('clients/<int:pk>/detail', ClientDetailView.as_view(), name='detail-client'),
    path('clients/<int:pk>/update', ClientUpdateView.as_view(), name="update-client"),
    path('clients/<int:pk>/delete', ClientDeleteView.as_view(), name="delete-client"),
    path('devis/detail', DevisListView.as_view(), name='list-devis'),
    path('devis/<int:pk>/detail', DevisDetailView.as_view(), name='detail-devis'),
    path('devis/new', DevisCreateView.as_view(), name='create-devis'),
    path('devis/<int:pk>/update', DevisUpdateView.as_view(), name='update-devis'),
    path('devis/<int:pk>/delete', DevisDeleteView.as_view(), name='delete-devis'),
    path('devis/<int:pk>/transform', TransformDevisToFactureView.as_view(), name='facture'),
    path('generate/<int:pk>/pdf', DevisPrintView.as_view(), name='generate_pdf'),
    path('facture/', FactureListView.as_view(), name='list-facture'),
    path('facture/<int:pk>/detail', FactureDetailView.as_view(), name='detail-facture'),
    path('generate/<int:pk>/pdf/facture', FacturePrintView.as_view(), name='generate_pdf_facture'),
    path('accounts/', include('django.contrib.auth.urls')),

   
    # path('adresss/',AdressView )
]

devis/models.py
from django.db import models
from django.db.models import Sum
from facturier.models import Client

# Create your models here.

class Devis(models.Model):

    client_devis = models.ForeignKey(Client, on_delete=models.CASCADE)
    date = models.DateField()

    def total_ht(self):
        result = 0
        for totht in self.linedevis.all():
            result += totht.sub_total()
        return result        

    def total_tva(self):
        result = 0
        result = self.total_ht() * (20/100)
        return result    

    def total_ttc(self):
        result = self.total_ht() * (1+(20/100))
        return result

class LineDevis(models.Model):

    description = models.CharField(max_length=100)
    qte = models.IntegerField()
    puht = models.FloatField()
    line = models.ForeignKey(Devis, on_delete=models.CASCADE, related_name='linedevis')
    
    def sub_total(self):
        return self.qte * self.puht

facture/models.py
from django.db import models
from devis.models import Devis
from facturier.models import Client
from django.db.models import signals
from django.dispatch import receiver
from datetime import date


class Facture(models.Model):

    client = models.ForeignKey(Client, null=True, on_delete=models.CASCADE)
    devis = models.OneToOneField(Devis, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)

    def total_ht(self):
        result = 0
        for totht in self.linefacture.all():
            result += totht.sub_total()
        return result        

    def total_tva(self):
        result = 0
        result = self.total_ht() * (20/100)
        return result    

    def total_ttc(self):
        result = self.total_ht() * (1+(20/100))
        return result

class LineFacture(models.Model):

    description = models.CharField(max_length=100)
    qte = models.IntegerField()
    puht = models.FloatField()
    line = models.ForeignKey(Facture, on_delete=models.CASCADE, related_name='linefacture')
    
    def sub_total(self):
        return self.qte * self.puht




@receiver(signals.post_save, sender=Facture)
def create_facture(sender, instance, created, **kwargs):
    if created:
        for linedevis in instance.devis.linedevis.all() :
            LineFacture.objects.create (
                description = linedevis.description,
                qte = linedevis.qte,
                puht = linedevis.puht,
                line = instance
            )
    else:
        print("not save")

facturier/models.py
from django.db import models

# Create your models here.

class Client(models.Model):

    def __str__(self):
        return self.raison_sociale

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    tel = models.IntegerField()
    raison_sociale = models.CharField(max_length=100)
    siret = models.IntegerField()
    tva = models.CharField(max_length=13)
    email = models.CharField(max_length=50)

class Address(models.Model):

    ADDRESS_CHOICES =[
        ('SH', 'Livraison'),
        ('BL', 'Facturation'),
        ('HQ', 'Siège Social'),
    ]
    addressType = models.CharField(max_length=15, choices=ADDRESS_CHOICES, blank=True)

    num = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=100, blank=True)
    complement = models.CharField(max_length=100, null=True, blank=True)
    zipcode = models.IntegerField(null=True, blank=True)
    town = models.CharField(max_length=50, null=True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

facturier/forms.py
from django.forms import inlineformset_factory
from .models import Client, Address
from django import forms


AddressInlineFormSet = inlineformset_factory(Client, Address, 
                                                fields = '__all__',
                                                exclude = ([]),
                                                can_delete = True,
                                                max_num = 5,
                                                extra = 1

)

facturier/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, CreateView, UpdateView, ModelFormMixin
from django.views.generic import TemplateView
from .models import Client, Address
from django.contrib.auth.forms import UserCreationForm
from facturier.forms import AddressInlineFormSet
from django.http import HttpResponseRedirect, HttpResponse
from django import forms

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin



class HomePageView(TemplateView):

    model = Client
    template_name = 'facturier/home.html'


class ClientCreateView(CreateView):

    model = Client
    fields = '__all__'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = CreateView.get_context_data(self, **kwargs)
        context["address_client"] = AddressInlineFormSet()
        return context

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        if form.is_valid():
            self.object = form.save(commit=False)
            address_form = AddressInlineFormSet(self.request.POST, self.request.FILES, instance = self.object)
            if address_form.is_valid():
                form.save()
                # form.save_m2m()
                address_form.save()
                # login(self.request, self.object)
                return HttpResponseRedirect(self.get_success_url())
    
        context = {
            'form' : form,
            'address_form' : address_form
        }
        return self.render_to_response(context)


class ClientListView(ListView):

    model = Client



class ClientDetailView(DetailView):

    model = Client



class ClientUpdateView(UpdateView):

    model = Client
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('detail-client', args = [self.object.id])

    def get_context_data(self, **kwargs):
        context = UpdateView.get_context_data(self, **kwargs)
        context["address_client"] = AddressInlineFormSet(instance=self.get_object())
        return context

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        address_form = AddressInlineFormSet(self.request.POST, instance = self.object)
        if form.is_valid() and address_form.is_valid():
            form.save()
            address_form.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            context = {
                'form' : form,
                'address_form' : address_form
            }
            return self.render_to_response(context)


    
class ClientDeleteView(PermissionRequiredMixin, DeleteView):

    model = Client
    success_url = reverse_lazy('list-client')

    permission_required = ('facturier.delete_facturier')


    # def get(self, request, *args, **kwargs):
    #     return self.post(request, *args, **kwargs)

# class AdressView(AdressView):

#     model = Client, Adress

facturier/templates/facturier/client_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="card mx-auto my-5" style="width: 25rem;">
    <h2 class="font-weight-bolder text-center">{{ client.raison_sociale }}</h2>
    <div class="card-body">
        <p><span class="font-weight-bolder">Nom : </span>{{ client.first_name }}</p>
        <p><span class="font-weight-bolder">Prenom : </span> {{ client.last_name }}</p>
        <p><span class="font-weight-bolder">N° SIRET : </span> {{ client.siret }}</p>
        <p><span class="font-weight-bolder">N° TVA : </span> {{ client.tva }}</p>
        <p><span class="font-weight-bolder">N° Tel : </span> {{ client.tel }}</p>
        <p><span class="font-weight-bolder">Email : </span> {{ client.email }}</p>
        {% for address in client.address_set.all %}
        <p><span class="font-weight-bolder">Address {{ address.addressType }} : </span> {{ address.address }}</p>
        {% endfor %}
        <p><a href="{% url 'update-client' client.id %}" class="btn btn-primary">Changer Infos</a></p>
    </div>
</div>

<div class="row">
    <div class="col-6">

        <h1 class="text-center mt-5 mb-5">Liste des Devis</h1>
        <table class="table table-striped w-75 mx-auto mb-5">
            <thead>
                <tr>
                    <th scope="col">N° devis</th>
                    <th scope="col">Nom Client</th>
                    <th scope="col">Raison Sociale</th>
                    <th scope="col">Date</th>
                    <!-- <th scope="col">Voir</th> -->
                    <!-- <th scope="col">Del</th> -->
                </tr>
            </thead>
            <tbody>
                {% for devis in client.devis_set.all %}
                <tr>
                    <th scope="row">{{ devis.id }}</th>
                    <td>{{ devis.client_devis.last_name }}</td>
                    <td>{{ devis.client_devis.raison_sociale }}</td>
                    <td>{{ devis.date }}</td>
        
                    <td><a href="{% url 'detail-devis' devis.id %}" class="text-dark">Consulter</a></td>
                    {% comment %}
                    <td><button data-toggle="modal" data-target="#supDevist{{ devis.client_devis.id }}"
                            class="btn btn-danger"><a href="#" class="text-white">Delete</a></button></td>
                    {% endcomment %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="col-6">
        
        <h1 class="text-center mt-5 mb-5">Liste des Factures</h1>
        <table class="table table-striped w-75 mx-auto mb-5">
            <thead>
                <tr>
                    <th scope="col">N° de Facture</th>
                    <th scope="col">Nom Client</th>
                    <th scope="col">Raison Sociale</th>
                    <th scope="col">Date</th>
                    <th scope="col">Voir</th>
                </tr>
            </thead>
            <tbody>
                {% for facture in client.facture_set.all %}
                <tr>
                    <th scope="row">{{ facture.id }}</th>
                    <td>{{ facture.client.last_name }}</td>
                    <td>{{ facture.client.raison_sociale }}</td>
                    <td>{{ facture.date }}</td>
                    <td><a href="{% url 'detail-facture' facture.id %}" class="text-dark">Consulter</a></td>
                    
                    {% comment %}
                    {% endcomment %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>

        {% endblock %}

facturier/templates/facturier/client_form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
<form id="newClient" method="post" enctype="multipart/form-data" class="w-50 mx-auto my-5">{% csrf_token %}
    {% bootstrap_form form %}
    {% for address_client in address_client.forms %}
    {% if address_client.instance.pk%}{{address_client.DELETE}}{% endif %}
    <div id="formAddress">
        {% bootstrap_form address_client %}
    </div>

    {% endfor %}

    {{ address_client.management_form }}
    <input class="last btn-primary btn mb-3" type="submit" value="Register">
</form>
{% endblock %}

facturier/templates/facturier/client_list.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
    <h1 class="text-center mt-5 mb-5">Liste des Clients</h1>
    <table class="table table-striped w-75 mx-auto mb-5">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Raison Sociale</th>
                <th scope="col">Voir</th>
                <th scope="col">Del</th>
            </tr>
        </thead>
        <tbody>
          {% for client in object_list %} 
          <tr>
            <th scope="row">{{ client.id }}</th>
            <td>{{ client.first_name }}</td>
            <td>{{ client.last_name }}</td>
            <td>{{ client.raison_sociale }}</td>
            <td><a href="{% url 'detail-client' client.id %}" class="text-dark">Consulter</a></td>
            <td><button data-toggle="modal" data-target="#supClient{{ client.id }}"  class="btn btn-danger"><a href="#" class="text-white">Delete</a></button></td>
          </tr>
          
          
          <div class="modal fade" id="supClient{{ client.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form method="POST" action="{% url 'delete-client' client.id%}">{% csrf_token %}
                  <p>Are you sure you want to delete {{ client.first_name }}?</p>
                  <input class="last" type="submit" value="Confirm">
                </form>
              </div>
              <!-- <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div> -->
            </div>
          </div>
        </div>
        {% endfor %}
      </tbody>
      </table>
{% endblock %}

facturier/templates/facturier/home.html
{% extends 'base.html' %}

{% block content %}
<div class="navMain">

    <h1 class="text-center pt-5 font-weight-bold">Nom Entreprise</h1>
    
    <div class="link d-flex justify-content-center">
        <p><a href="{% url 'register' %}" class="mx-3">Créer un Nouveau Client</a></p>
        <p><a href="{% url 'list-client' %}" class="mx-3">Liste des Clients</a></p>
        <p><a href="{% url 'list-devis' %}" class="mx-3">Liste des Devis</a></p>
        <p><a href="{% url 'create-devis' %}" class="mx-3">Créer un Devis</a></p>
        <p><a href="{% url 'list-facture' %}" class="mx-3">Liste des Factures</a></p>
        
    </div>

</div>



{% endblock %}